### ISSUE TITLE
Incompatible with androidx projects

### ISSUE THREAD

**Issue by kylpo** [alexfacciorusso/DaggerViewModel#4]
Just a heads-up that this lib does not work with my new project using `androidx`. Locally updating imports to `androidx.lifecycle.ViewModel` and `androidx.lifecycle.ViewModelProvider` works.

Would you like a PR with these changes?

**Comment by alexfacciorusso** [comment]
AndroidX is actually in alpha. I think could be possible to have an experimental branch with those changes, and if you want, contributions are accepted!
Then when androidx will become stable, we could merge those changes in the main branch.

**Comment by kylpo** [comment]
Yeah, good idea to wait until stable. I've gotten burned a couple times already and am considering dropping `androidx` until stable as well.

**Comment by roeyf** [comment]
I am using your project for activity and view models and it works great. Because my project using androidx  fragments the project doesn't work properly in this case. When do you intend to support it?

**Comment by alexfacciorusso** [comment]
Definitely updating this library is in my plans; I'll try to pack an update as soon as possible, so stay tuned!

**Comment by alexfacciorusso** [comment]
Version 0.2.0 released with AndroidX support!
